services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa_development
      POSTGRES_DB: medusa_development
    volumes:
      - postgres_data_prod:/var/lib/postgresql
    networks:
      - default
      - traefik
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@medusa.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - default
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/pgadmin`)"
      - "traefik.http.routers.pgadmin-router.entrypoints=https"
      - "traefik.http.routers.pgadmin-router.middlewares=pgadmin-stripprefix"
      - "traefik.http.routers.pgadmin-router.service=pgadmin-service"
      - "traefik.http.middlewares.pgadmin-stripprefix.stripprefix.prefixes=/pgadmin"
      - "traefik.http.services.pgadmin-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 80"
    volumes:
      #- .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: medusa
      DATABASE_PASSWORD: medusa_development
      DATABASE_NAME: medusa_development
      RAILS_ENV: production
      RACK_ENV: production
    stdin_open: true
    tty: true
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esm-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/esm`)"
      - "traefik.http.routers.esm-router.entrypoints=https"
      - "traefik.http.routers.esm-router.middlewares=esm-stripprefix"
      - "traefik.http.routers.esm-router.service=esm-service"
      - "traefik.http.middlewares.esm-stripprefix.stripprefix.prefixes=/esm"
      - "traefik.http.services.esm-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
volumes:
  postgres_data_prod:
  pgadmin_data:
  bundle_cache:
  node_modules:
networks:
  traefik:
    external: true