services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa_development
      POSTGRES_DB: medusa_development
    volumes:
      - postgres_data_prod:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - default
      - traefik
    restart: unless-stopped
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 80"
    volumes:
      #- .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: medusa
      DATABASE_PASSWORD: medusa_development
      DATABASE_NAME: medusa_development
      RAILS_ENV: production
      RACK_ENV: production
    stdin_open: true
    tty: true
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esm-router.rule=Host(`env.rz-vm182.gfz.de`) && PathPrefix(`/esm`)"
      - "traefik.http.routers.esm-router.entrypoints=https"
      - "traefik.http.routers.esm-router.middlewares=esm-stripprefix"
      - "traefik.http.routers.esm-router.service=esm-service"
      - "traefik.http.middlewares.esm-stripprefix.stripprefix.prefixes=/esm"
      - "traefik.http.services.esm-service.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik"
volumes:
  postgres_data_prod:
  bundle_cache:
  node_modules:
networks:
  traefik:
    external: true